# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/chord.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/chord.proto\x12\x05\x63hord\"\'\n\x08NodeInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"\"\n\x14\x46indSuccessorRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xcb\x01\n\x0c\x43hordService\x12=\n\rFindSuccessor\x12\x1b.chord.FindSuccessorRequest\x1a\x0f.chord.NodeInfo\x12/\n\x0eGetPredecessor\x12\x0c.chord.Empty\x1a\x0f.chord.NodeInfo\x12\'\n\x06Notify\x12\x0f.chord.NodeInfo\x1a\x0c.chord.Empty\x12\"\n\x04Ping\x12\x0c.chord.Empty\x1a\x0c.chord.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.chord_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NODEINFO']._serialized_start=28
  _globals['_NODEINFO']._serialized_end=67
  _globals['_FINDSUCCESSORREQUEST']._serialized_start=69
  _globals['_FINDSUCCESSORREQUEST']._serialized_end=103
  _globals['_EMPTY']._serialized_start=105
  _globals['_EMPTY']._serialized_end=112
  _globals['_CHORDSERVICE']._serialized_start=115
  _globals['_CHORDSERVICE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
