# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import chord_pb2 as proto_dot_chord__pb2


class ChordServiceStub(object):
    """Chord DHT Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindSuccessor = channel.unary_unary(
                '/chord.ChordService/FindSuccessor',
                request_serializer=proto_dot_chord__pb2.FindSuccessorRequest.SerializeToString,
                response_deserializer=proto_dot_chord__pb2.NodeInfo.FromString,
                )
        self.GetPredecessor = channel.unary_unary(
                '/chord.ChordService/GetPredecessor',
                request_serializer=proto_dot_chord__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_chord__pb2.NodeInfo.FromString,
                )
        self.Notify = channel.unary_unary(
                '/chord.ChordService/Notify',
                request_serializer=proto_dot_chord__pb2.NodeInfo.SerializeToString,
                response_deserializer=proto_dot_chord__pb2.Empty.FromString,
                )
        self.Ping = channel.unary_unary(
                '/chord.ChordService/Ping',
                request_serializer=proto_dot_chord__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_chord__pb2.Empty.FromString,
                )


class ChordServiceServicer(object):
    """Chord DHT Service
    """

    def FindSuccessor(self, request, context):
        """Find successor of a given ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPredecessor(self, request, context):
        """Get the predecessor of this node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Notify(self, request, context):
        """Notify this node that there will another node might be its predecessor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Check if the node is alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChordServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindSuccessor': grpc.unary_unary_rpc_method_handler(
                    servicer.FindSuccessor,
                    request_deserializer=proto_dot_chord__pb2.FindSuccessorRequest.FromString,
                    response_serializer=proto_dot_chord__pb2.NodeInfo.SerializeToString,
            ),
            'GetPredecessor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredecessor,
                    request_deserializer=proto_dot_chord__pb2.Empty.FromString,
                    response_serializer=proto_dot_chord__pb2.NodeInfo.SerializeToString,
            ),
            'Notify': grpc.unary_unary_rpc_method_handler(
                    servicer.Notify,
                    request_deserializer=proto_dot_chord__pb2.NodeInfo.FromString,
                    response_serializer=proto_dot_chord__pb2.Empty.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=proto_dot_chord__pb2.Empty.FromString,
                    response_serializer=proto_dot_chord__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chord.ChordService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChordService(object):
    """Chord DHT Service
    """

    @staticmethod
    def FindSuccessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chord.ChordService/FindSuccessor',
            proto_dot_chord__pb2.FindSuccessorRequest.SerializeToString,
            proto_dot_chord__pb2.NodeInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPredecessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chord.ChordService/GetPredecessor',
            proto_dot_chord__pb2.Empty.SerializeToString,
            proto_dot_chord__pb2.NodeInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Notify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chord.ChordService/Notify',
            proto_dot_chord__pb2.NodeInfo.SerializeToString,
            proto_dot_chord__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chord.ChordService/Ping',
            proto_dot_chord__pb2.Empty.SerializeToString,
            proto_dot_chord__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
